import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const navList = [
    { name: "Home", href: "/" },
    { name: "Props", href: "/props" },
    { name: "Params", href: "/props/params" },
    { name: "SearchParams", href: "/props/searchparams?key=value" },
    { name: "Client Component", href: "/client-component" },
    { name: "+ip", href: "/api/ip" },
    { name: "+time", href: "/api/time" },
  ];

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="bg-gray-300 p-5 mb-4">
          {navList.map((item, idx) => (
            <span key={item.href}>
              <Link href={item.href}>{item.name}</Link>
              {idx < navList.length - 1 ? " | " : ""}
            </span>
          ))}
        </div>
        {children}
      </body>
    </html>
  );
}
